// app/layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import Header from "@/components/header";
import { UserProvider } from "@/src/context/UserContext";

// Import the UserProvider you created
// import { UserProvider } from "@/context/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo - To manage your tasks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} relative`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          {/* Wrap the app with UserProvider */}
          <UserProvider>
            {/* ✅ Background Grid */}
            <div className="grid-background fixed top-0 left-0 w-full h-full z-[-1]" />

            <Header />

            <main className="relative min-h-screen">{children}</main>

            <Toaster richColors />

            <footer className="bg-muted/60 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made by Rehan.S</p>
              </div>
            </footer>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
